// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Header documents */
interface HeaderDocumentData {
    /**
     * Title field in *Header*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Site Title
     * - **API ID Path**: header.Title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    Title: prismicT.KeyTextField;
    /**
     * Logo field in *Header*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: header.Logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    Logo: prismicT.ImageField<never>;
    /**
     * Select Menu field in *Header*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: header.SelectMenu
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    SelectMenu: prismicT.RelationField<"menu">;
}
/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HeaderDocumentData>, "header", Lang>;
/** Content for Menu documents */
interface MenuDocumentData {
    /**
     * Menu  field in *Menu*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.Menu[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    Menu: prismicT.GroupField<Simplify<MenuDocumentDataMenuItem>>;
}
/**
 * Item in Menu → Menu
 *
 */
export interface MenuDocumentDataMenuItem {
    /**
     * Menu Label field in *Menu → Menu *
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.Menu[].MenuLabel
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    MenuLabel: prismicT.KeyTextField;
    /**
     * Menu Link field in *Menu → Menu *
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.Menu[].MenuLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    MenuLink: prismicT.LinkField;
    /**
     * Sub Menu field in *Menu → Menu *
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.Menu[].SubMenu
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    SubMenu: prismicT.RelationField<"menu">;
}
/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<MenuDocumentData>, "menu", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = HeroSectionSlice | BrandsLogoSlice | ContentSectionSlice | HeaderTitleSlice | ImageWithContentSlice | BannerSectionSlice | ServicesSlice | TestimonialsSlice | BlogSlice | FaqSlice | PricingSlice | TeamSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Setting documents */
interface SettingDocumentData {
    /**
     * Site Title field in *Setting*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: setting.SiteTitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    SiteTitle: prismicT.KeyTextField;
    /**
     * Logo field in *Setting*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: setting.Logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    Logo: prismicT.ImageField<never>;
    /**
     * E-mail field in *Setting*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: setting.Email
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    Email: prismicT.LinkField;
    /**
     * E-Mail Icom field in *Setting*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: setting.EmailIcon
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    EmailIcon: prismicT.KeyTextField;
    /**
     * Phone field in *Setting*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: setting.Phone
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    Phone: prismicT.KeyTextField;
    /**
     * Phone Icon field in *Setting*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: setting.PhoneIcon
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    PhoneIcon: prismicT.KeyTextField;
    /**
     * CopyRight Text field in *Setting*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: setting.CopyRightText
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    CopyRightText: prismicT.KeyTextField;
    /**
     * Socail field in *Setting*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: setting.Socail[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    Socail: prismicT.GroupField<Simplify<SettingDocumentDataSocailItem>>;
}
/**
 * Item in Setting → Socail
 *
 */
export interface SettingDocumentDataSocailItem {
    /**
     * Icon field in *Setting → Socail*
     *
     * - **Field Type**: Text
     * - **Placeholder**: add icon name exaple  twitter
     * - **API ID Path**: setting.Socail[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    icon: prismicT.KeyTextField;
    /**
     * Link field in *Setting → Socail*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: setting.Socail[].IconLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    IconLink: prismicT.LinkField;
}
/**
 * Setting document from Prismic
 *
 * - **API ID**: `setting`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SettingDocumentData>, "setting", Lang>;
export type AllDocumentTypes = HeaderDocument | MenuDocument | PageDocument | SettingDocument;
/**
 * Primary content in BannerSection → Primary
 *
 */
interface BannerSectionSliceDefaultPrimary {
    /**
     * Background Image field in *BannerSection → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_section.primary.BackgroundImage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    BackgroundImage: prismicT.ImageField<never>;
    /**
     * Video Link field in *BannerSection → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_section.primary.VideoLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    VideoLink: prismicT.LinkField;
    /**
     * Video Icon field in *BannerSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_section.primary.VideoIcon
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    VideoIcon: prismicT.KeyTextField;
    /**
     * Title field in *BannerSection → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: banner_section.primary.Title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Title: prismicT.TitleField;
    /**
     * Description field in *BannerSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your product
     * - **API ID Path**: banner_section.primary.Description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Description: prismicT.RichTextField;
    /**
     * Action Label field in *BannerSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_section.primary.ActionLabel
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    ActionLabel: prismicT.KeyTextField;
    /**
     * Action Link field in *BannerSection → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_section.primary.ActionLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    ActionLink: prismicT.LinkField;
}
/**
 * Default variation for BannerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BannerSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<BannerSectionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *BannerSection*
 *
 */
type BannerSectionSliceVariation = BannerSectionSliceDefault;
/**
 * BannerSection Shared Slice
 *
 * - **API ID**: `banner_section`
 * - **Description**: `BannerSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSectionSlice = prismicT.SharedSlice<"banner_section", BannerSectionSliceVariation>;
/**
 * Primary content in Blogs → Primary
 *
 */
interface BlogSliceDefaultPrimary {
    /**
     * Title field in *Blogs → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: blog.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Blogs → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your product
     * - **API ID Path**: blog.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Blogs Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Blog`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<BlogSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Blogs*
 *
 */
type BlogSliceVariation = BlogSliceDefault;
/**
 * Blogs Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: `Blog`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogSlice = prismicT.SharedSlice<"blog", BlogSliceVariation>;
/**
 * Primary content in BrandsLogo → Primary
 *
 */
interface BrandsLogoSliceDefaultPrimary {
    /**
     * Title field in *BrandsLogo → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: brands_logo.primary.Title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    Title: prismicT.KeyTextField;
}
/**
 * Item in BrandsLogo → Items
 *
 */
export interface BrandsLogoSliceDefaultItem {
    /**
     * Brand Image field in *BrandsLogo → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: brands_logo.items[].BrandImage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    BrandImage: prismicT.ImageField<never>;
}
/**
 * Default variation for BrandsLogo Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BrandsLogo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BrandsLogoSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<BrandsLogoSliceDefaultPrimary>, Simplify<BrandsLogoSliceDefaultItem>>;
/**
 * Slice variation for *BrandsLogo*
 *
 */
type BrandsLogoSliceVariation = BrandsLogoSliceDefault;
/**
 * BrandsLogo Shared Slice
 *
 * - **API ID**: `brands_logo`
 * - **Description**: `BrandsLogo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BrandsLogoSlice = prismicT.SharedSlice<"brands_logo", BrandsLogoSliceVariation>;
/**
 * Primary content in ContentSection → Primary
 *
 */
interface ContentSectionSliceDefaultPrimary {
    /**
     * Title field in *ContentSection → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: content_section.primary.Title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Title: prismicT.TitleField;
    /**
     * Description field in *ContentSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your product
     * - **API ID Path**: content_section.primary.Description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Description: prismicT.RichTextField;
    /**
     * List Style field in *ContentSection → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: select list style
     * - **API ID Path**: content_section.primary.ListStyle
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    ListStyle: prismicT.SelectField<"round" | "square">;
}
/**
 * Default variation for ContentSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ContentSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ContentSectionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ContentSection*
 *
 */
type ContentSectionSliceVariation = ContentSectionSliceDefault;
/**
 * ContentSection Shared Slice
 *
 * - **API ID**: `content_section`
 * - **Description**: `ContentSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSectionSlice = prismicT.SharedSlice<"content_section", ContentSectionSliceVariation>;
/**
 * Primary content in Faq → Primary
 *
 */
interface FaqSliceDefaultPrimary {
    /**
     * Title field in *Faq → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: faq.primary.Title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Title: prismicT.RichTextField;
    /**
     * Description field in *Faq → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your product
     * - **API ID Path**: faq.primary.Description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Description: prismicT.RichTextField;
}
/**
 * Item in Faq → Items
 *
 */
export interface FaqSliceDefaultItem {
    /**
     * Question field in *Faq → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.items[].Question
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Question: prismicT.TitleField;
    /**
     * Answer field in *Faq → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.items[].Answer
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Answer: prismicT.RichTextField;
}
/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FaqSliceDefaultPrimary>, Simplify<FaqSliceDefaultItem>>;
/**
 * Slice variation for *Faq*
 *
 */
type FaqSliceVariation = FaqSliceDefault;
/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSlice = prismicT.SharedSlice<"faq", FaqSliceVariation>;
/**
 * Primary content in HeaderTitle → Primary
 *
 */
interface HeaderTitleSliceDefaultPrimary {
    /**
     * Title field in *HeaderTitle → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: header_title.primary.Title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Title: prismicT.TitleField;
    /**
     * Description field in *HeaderTitle → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your product
     * - **API ID Path**: header_title.primary.Description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Description: prismicT.RichTextField;
}
/**
 * Default variation for HeaderTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeaderTitle`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderTitleSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeaderTitleSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HeaderTitle*
 *
 */
type HeaderTitleSliceVariation = HeaderTitleSliceDefault;
/**
 * HeaderTitle Shared Slice
 *
 * - **API ID**: `header_title`
 * - **Description**: `HeaderTitle`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderTitleSlice = prismicT.SharedSlice<"header_title", HeaderTitleSliceVariation>;
/**
 * Primary content in HeroSection → Primary
 *
 */
interface HeroSectionSliceDefaultPrimary {
    /**
     * Title field in *HeroSection → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: hero_section.primary.Title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Title: prismicT.TitleField;
    /**
     * Description field in *HeroSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your product
     * - **API ID Path**: hero_section.primary.Description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Description: prismicT.RichTextField;
    /**
     * Cta Button field in *HeroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.CtaButton
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    CtaButton: prismicT.KeyTextField;
    /**
     * Cta Button Link field in *HeroSection → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.CtaButtonLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    CtaButtonLink: prismicT.LinkField;
    /**
     * Right Image field in *HeroSection → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.RightImage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    RightImage: prismicT.ImageField<never>;
    /**
     * Video field in *HeroSection → Primary*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: add your video
     * - **API ID Path**: hero_section.primary.Video
     * - **Documentation**: https://prismic.io/docs/core-concepts/embed
     *
     */
    Video: prismicT.EmbedField;
    /**
     * Video Link field in *HeroSection → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.VideoLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    VideoLink: prismicT.LinkField;
}
/**
 * Item in HeroSection → Items
 *
 */
export interface HeroSectionSliceDefaultItem {
    /**
     * Card Icon field in *HeroSection → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.items[].CardIcon
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    CardIcon: prismicT.KeyTextField;
    /**
     * Label field in *HeroSection → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.items[].Label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    Label: prismicT.KeyTextField;
    /**
     * Link field in *HeroSection → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.items[].Link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    Link: prismicT.LinkField;
}
/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSectionSliceDefaultPrimary>, Simplify<HeroSectionSliceDefaultItem>>;
/**
 * Slice variation for *HeroSection*
 *
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;
/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: `HeroSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSectionSlice = prismicT.SharedSlice<"hero_section", HeroSectionSliceVariation>;
/**
 * Primary content in ImageWithContent → Primary
 *
 */
interface ImageWithContentSliceDefaultPrimary {
    /**
     * Main Image field in *ImageWithContent → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_with_content.primary.MainImage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    MainImage: prismicT.ImageField<never>;
}
/**
 * Item in ImageWithContent → Items
 *
 */
export interface ImageWithContentSliceDefaultItem {
    /**
     * Quantity field in *ImageWithContent → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_with_content.items[].Quantity
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    Quantity: prismicT.KeyTextField;
    /**
     * Description field in *ImageWithContent → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_with_content.items[].Description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Description: prismicT.RichTextField;
}
/**
 * Default variation for ImageWithContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageWithContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageWithContentSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageWithContentSliceDefaultPrimary>, Simplify<ImageWithContentSliceDefaultItem>>;
/**
 * Slice variation for *ImageWithContent*
 *
 */
type ImageWithContentSliceVariation = ImageWithContentSliceDefault;
/**
 * ImageWithContent Shared Slice
 *
 * - **API ID**: `image_with_content`
 * - **Description**: `ImageWithContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageWithContentSlice = prismicT.SharedSlice<"image_with_content", ImageWithContentSliceVariation>;
/**
 * Primary content in Pricing → Primary
 *
 */
interface PricingSliceDefaultPrimary {
    /**
     * Title field in *Pricing → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: pricing.primary.Title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Title: prismicT.TitleField;
    /**
     * Description field in *Pricing → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pricing.primary.Description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Description: prismicT.RichTextField;
}
/**
 * Item in Pricing → Items
 *
 */
export interface PricingSliceDefaultItem {
    /**
     * Heading field in *Pricing → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: pricing.items[].Heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Heading: prismicT.TitleField;
    /**
     * Icon field in *Pricing → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pricing.items[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    icon: prismicT.KeyTextField;
    /**
     * Amont field in *Pricing → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pricing.items[].Amont
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Amont: prismicT.RichTextField;
    /**
     * Duration field in *Pricing → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pricing.items[].Duration
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Duration: prismicT.RichTextField;
    /**
     * List field in *Pricing → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pricing.items[].List
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    List: prismicT.RichTextField;
    /**
     * Buy Now field in *Pricing → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pricing.items[].BuyNow
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    BuyNow: prismicT.KeyTextField;
    /**
     * Buy Now Link field in *Pricing → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: pricing.items[].BuyNowLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    BuyNowLink: prismicT.LinkField;
}
/**
 * Default variation for Pricing Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Pricing`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PricingSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<PricingSliceDefaultPrimary>, Simplify<PricingSliceDefaultItem>>;
/**
 * Slice variation for *Pricing*
 *
 */
type PricingSliceVariation = PricingSliceDefault;
/**
 * Pricing Shared Slice
 *
 * - **API ID**: `pricing`
 * - **Description**: `Pricing`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PricingSlice = prismicT.SharedSlice<"pricing", PricingSliceVariation>;
/**
 * Primary content in Services → Primary
 *
 */
interface ServicesSliceDefaultPrimary {
    /**
     * Title field in *Services → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: services.primary.Title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Title: prismicT.TitleField;
}
/**
 * Item in Services → Items
 *
 */
export interface ServicesSliceDefaultItem {
    /**
     * Icon field in *Services → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].Icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    Icon: prismicT.KeyTextField;
    /**
     * Title field in *Services → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].Title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Title: prismicT.RichTextField;
    /**
     * Description field in *Services → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].Description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Description: prismicT.RichTextField;
    /**
     * Read More label field in *Services → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].ReadMorelabel
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    ReadMorelabel: prismicT.KeyTextField;
    /**
     * Read More Link field in *Services → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].ReadMoreLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    ReadMoreLink: prismicT.LinkField;
}
/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Services`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServicesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ServicesSliceDefaultPrimary>, Simplify<ServicesSliceDefaultItem>>;
/**
 * Slice variation for *Services*
 *
 */
type ServicesSliceVariation = ServicesSliceDefault;
/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: `Services`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServicesSlice = prismicT.SharedSlice<"services", ServicesSliceVariation>;
/**
 * Item in Team → Items
 *
 */
export interface TeamSliceDefaultItem {
    /**
     * Profie field in *Team → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: team.items[].Profie
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    Profie: prismicT.ImageField<never>;
    /**
     * Author field in *Team → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: team.items[].Author
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Author: prismicT.RichTextField;
    /**
     * Designation field in *Team → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: team.items[].Designation
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Designation: prismicT.RichTextField;
    /**
     * Socail Media field in *Team → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: team.items[].SocailMedia
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    SocailMedia: prismicT.RelationField;
}
/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Team`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TeamSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<TeamSliceDefaultItem>>;
/**
 * Slice variation for *Team*
 *
 */
type TeamSliceVariation = TeamSliceDefault;
/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: `Team`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TeamSlice = prismicT.SharedSlice<"team", TeamSliceVariation>;
/**
 * Primary content in Testimonials → Primary
 *
 */
interface TestimonialsSliceDefaultPrimary {
    /**
     * Title field in *Testimonials → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: testimonials.primary.Title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Title: prismicT.TitleField;
}
/**
 * Item in Testimonials → Items
 *
 */
export interface TestimonialsSliceDefaultItem {
    /**
     * Profile field in *Testimonials → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials.items[].Profile
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    Profile: prismicT.ImageField<never>;
    /**
     * Author field in *Testimonials → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials.items[].Author
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Author: prismicT.RichTextField;
    /**
     * Designation field in *Testimonials → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials.items[].Designation
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Designation: prismicT.RichTextField;
    /**
     * Raiting field in *Testimonials → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials.items[].Raiting
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    Raiting: prismicT.SelectField<"5" | "4" | "3" | "2" | "1">;
    /**
     * Description field in *Testimonials → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials.items[].Description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    Description: prismicT.RichTextField;
}
/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Testimonials`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TestimonialsSliceDefaultPrimary>, Simplify<TestimonialsSliceDefaultItem>>;
/**
 * Slice variation for *Testimonials*
 *
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;
/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: `Testimonials`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsSlice = prismicT.SharedSlice<"testimonials", TestimonialsSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HeaderDocumentData, HeaderDocument, MenuDocumentData, MenuDocumentDataMenuItem, MenuDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, SettingDocumentData, SettingDocumentDataSocailItem, SettingDocument, AllDocumentTypes, BannerSectionSliceDefaultPrimary, BannerSectionSliceDefault, BannerSectionSliceVariation, BannerSectionSlice, BlogSliceDefaultPrimary, BlogSliceDefault, BlogSliceVariation, BlogSlice, BrandsLogoSliceDefaultPrimary, BrandsLogoSliceDefaultItem, BrandsLogoSliceDefault, BrandsLogoSliceVariation, BrandsLogoSlice, ContentSectionSliceDefaultPrimary, ContentSectionSliceDefault, ContentSectionSliceVariation, ContentSectionSlice, FaqSliceDefaultPrimary, FaqSliceDefaultItem, FaqSliceDefault, FaqSliceVariation, FaqSlice, HeaderTitleSliceDefaultPrimary, HeaderTitleSliceDefault, HeaderTitleSliceVariation, HeaderTitleSlice, HeroSectionSliceDefaultPrimary, HeroSectionSliceDefaultItem, HeroSectionSliceDefault, HeroSectionSliceVariation, HeroSectionSlice, ImageWithContentSliceDefaultPrimary, ImageWithContentSliceDefaultItem, ImageWithContentSliceDefault, ImageWithContentSliceVariation, ImageWithContentSlice, PricingSliceDefaultPrimary, PricingSliceDefaultItem, PricingSliceDefault, PricingSliceVariation, PricingSlice, ServicesSliceDefaultPrimary, ServicesSliceDefaultItem, ServicesSliceDefault, ServicesSliceVariation, ServicesSlice, TeamSliceDefaultItem, TeamSliceDefault, TeamSliceVariation, TeamSlice, TestimonialsSliceDefaultPrimary, TestimonialsSliceDefaultItem, TestimonialsSliceDefault, TestimonialsSliceVariation, TestimonialsSlice };
    }
}
