// Code generated by Slice Machine. DO NOT EDIT.

import BannerSection from './BannerSection';
import Blogs from './Blogs';
import BrandsLogo from './BrandsLogo';
import ContentSection from './ContentSection';
import Faq from './Faq';
import HeaderTitle from './HeaderTitle';
import HeroSection from './HeroSection';
import ImageWithContent from './ImageWithContent';
import Pricing from './Pricing';
import Services from './Services';
import Team from './Team';
import Testimonials from './Testimonials';

export {
	BannerSection,
	Blogs,
	BrandsLogo,
	ContentSection,
	Faq,
	HeaderTitle,
	HeroSection,
	ImageWithContent,
	Pricing,
	Services,
	Team,
	Testimonials,
};

export const components = {
	banner_section: BannerSection,
	blog: Blogs,
	brands_logo: BrandsLogo,
	content_section: ContentSection,
	faq: Faq,
	header_title: HeaderTitle,
	hero_section: HeroSection,
	image_with_content: ImageWithContent,
	pricing: Pricing,
	services: Services,
	team: Team,
	testimonials: Testimonials,
};
